=== safesoftware/fme-packager/fme_packager/summarizer_spec.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "title": "FME Package Manifest",
    "description": "Manifest describing the content of an FME Package",
    "definitions": {
        "author": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "name": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                }
            },
            "required": [
                "name"
            ]
        },
        "format": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "name": {
                    "type": "string"
                },
                "short_name": {
                    "type": "string"
                },
                "categories": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "description": {
                    "type": "string"
                },
                "description_format": {
                    "type": "string",
                    "enum": [
                        "md",
                        "text",
                        "html"
                    ]
                },
                "fds_info": {
                    "type": "string"
                },
                "visible": {
                    "type": "boolean"
                }
            },
            "required": [
                "name",
                "short_name",
                "categories",
                "description",
                "description_format",
                "fds_info",
                "visible"
            ]
        },
        "transformer": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "name": {
                    "type": "string"
                },
                "latest_version": {
                    "type": "integer"
                },
                "versions": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "name": {
                                "type": "string"
                            },
                            "version": {
                                "type": "integer"
                            },
                            "categories": {
                                "type": "array",
                                "items": {
                                    "type": "string"
                                }
                            },
                            "aliases": {
                                "type": "array",
                                "items": {
                                    "type": "string"
                                }
                            },
                            "visible": {
                                "type": "boolean"
                            },
                            "data_processing_types": {
                                "type": "array",
                                "items": {
                                    "type": "string",
                                    "enum": [
                                        "both",
                                        "neither",
                                        "source",
                                        "destination"
                                    ]
                                }
                            }
                        },
                        "required": [
                            "name",
                            "version",
                            "categories",
                            "aliases",
                            "visible"
                        ]
                    }
                },
                "description": {
                    "type": "string"
                },
                "description_format": {
                    "type": "string",
                    "enum": [
                        "md",
                        "text",
                        "html"
                    ]
                }
            },
            "required": [
                "name",
                "latest_version",
                "versions",
                "description",
                "description_format"
            ]
        },
        "web_service": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "name": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "markdown_description": {
                    "type": "string"
                },
                "connection_description": {
                    "type": "string"
                },
                "markdown_connection_description": {
                    "type": "string"
                },
                "help_url": {
                    "type": "string"
                }
            },
            "required": [
                "name",
                "description",
                "markdown_description",
                "connection_description",
                "markdown_connection_description",
                "help_url"
            ]
        },
        "web_filesystem": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "name": {
                    "type": "string"
                }
            },
            "required": [
                "name"
            ]
        },
        "python_package": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "name": {
                    "type": "string"
                }
            },
            "required": [
                "name"
            ]
        },
        "entry_point": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "platform": {
                    "type": "string"
                },
                "entry_point": {
                    "type": "string"
                }
            },
            "required": [
                "platform",
                "entry_point"
            ]
        },
        "background_worker": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "name": {
                    "type": "string"
                },
                "entry_points": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "$ref": "#/definitions/entry_point"
                    }
                }
            },
            "required": [
                "name",
                "entry_points"
            ]
        }
    },
    "type": "object",
    "required": [
        "fpkg_version",
        "uid",
        "publisher_uid",
        "name",
        "description",
        "deprecated",
        "version",
        "minimum_fme_build",
        "author",
        "package_content",
        "categories"
    ],
    "additionalProperties": false,
    "properties": {
        "fpkg_version": {
            "description": "Format version for the package",
            "type": "integer",
            "enum": [
                1
            ]
        },
        "uid": {
            "description": "Unique identifier for the package",
            "type": "string",
            "pattern": "^[a-z0-9](?!.*--)[a-z0-9-]{1,30}[a-z0-9]$"
        },
        "publisher_uid": {
            "description": "Unique identifier for the package publisher",
            "type": "string",
            "pattern": "^[a-z0-9](?!.*--)[a-z0-9-]{1,30}[a-z0-9]$"
        },
        "name": {
            "description": "Name of the package",
            "type": "string"
        },
        "description": {
            "description": "Short description of the package purpose and content",
            "type": "string"
        },
        "deprecated": {
            "description": "Indicates if the package is deprecated",
            "type": "boolean"
        },
        "version": {
            "description": "Version of the package, using semantic versioning",
            "type": "string",
            "pattern": "^[0-9]{1,9}\\.[0-9]{1,9}\\.[0-9]{1,9}$"
        },
        "minimum_fme_build": {
            "description": "Minimum FME build to use the package",
            "type": "integer",
            "minimum": 19000
        },
        "unsupported_from_build": {
            "description": "This package is unsupported starting from this FME Build",
            "type": "integer",
            "minimum": 26000
        },
        "author": {
            "description": "Author of the package",
            "type": "object",
            "$ref": "#/definitions/author"
        },
        "categories": {
            "description": "Categories for the package",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "package_content": {
            "description": "Components included in the package and to be deployed when the package is installed",
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "formats": {
                    "description": "Formats included in the package",
                    "type": "array",
                    "items": {
                        "type": "object",
                        "$ref": "#/definitions/format"
                    },
                    "uniqueItems": true
                },
                "transformers": {
                    "description": "Transformers included in the package",
                    "type": "array",
                    "items": {
                        "type": "object",
                        "$ref": "#/definitions/transformer"
                    },
                    "uniqueItems": true
                },
                "web_services": {
                    "description": "Web services included in the package",
                    "type": "array",
                    "items": {
                        "type": "object",
                        "$ref": "#/definitions/web_service"
                    },
                    "uniqueItems": true
                },
                "web_filesystems": {
                    "description": "Web file systems included in the package",
                    "type": "array",
                    "items": {
                        "type": "object",
                        "$ref": "#/definitions/web_filesystem"
                    },
                    "uniqueItems": true
                },
                "python_packages": {
                    "description": "Python packages included in the package",
                    "type": "array",
                    "items": {
                        "type": "object",
                        "$ref": "#/definitions/python_package"
                    },
                    "uniqueItems": true
                },
                "background_workers": {
                    "description": "Background workers included in the package",
                    "type": "array",
                    "items": {
                        "type": "object",
                        "$ref": "#/definitions/background_worker"
                    },
                    "uniqueItems": true
                }
            }
        }
    }
}

=== safesoftware/fme-packager/tests/fixtures/json_output/summarize_example.empty.json
{
    "fpkg_version": 1,
    "uid": "my-package",
    "publisher_uid": "example",
    "name": "My FME Package",
    "description": "A short description of my FME Package.",
    "deprecated": false,
    "version": "0.1.0",
    "minimum_fme_build": 19238,
    "author": {
        "name": "G Raymond",
        "email": "me@example.com"
    },
    "package_content": {
        "transformers": [],
        "formats": []
    },
    "categories": []
}

=== safesoftware/fme-packager/tests/fixtures/json_output/summarize_example.my-format-0.1.0.fpkg.json
{
  "fpkg_version": 1,
  "uid": "my-format",
  "publisher_uid": "example",
  "name": "My Example Format",
  "description": "A short description of my FME Package.",
  "deprecated": false,
  "version": "0.1.0",
  "minimum_fme_build": 21261,
  "author": {
    "name": "Safe Software"
  },
  "package_content": {
    "formats": [
      {
        "name": "example.my-format.format_name",
        "short_name": "format_name",
        "description": "A short description of my FME Package.\n",
        "description_format": "md",
        "visible": true,
        "fds_info": "EXAMPLE.MY-FORMAT.FORMAT_NAME|Format Name|NONE|BOTH|NONE|NO||NON_SPATIAL|NO|YES|YES|YES|1|1|example.my-format.My Example Format|NO|My Example Format|Database,Strings",
        "categories": [
          "Database",
          "Strings"
        ]
      }
    ],
    "python_packages": [
      {
        "name": "fme_my_format"
      }
    ],
    "transformers": []
  },
  "categories": [
    "Database",
    "Strings"
  ]
}

=== safesoftware/fme-packager/tests/fixtures/json_output/summarize_example.my-package-deprecated-0.1.0.fpkg.json
{
    "fpkg_version": 1,
    "uid": "my-package-deprecated",
    "publisher_uid": "example",
    "name": "My FME Package",
    "description": "A short description of my FME Package.",
    "deprecated": true,
    "version": "0.1.0",
    "minimum_fme_build": 19238,
    "author": {
        "name": "G Raymond",
        "email": "me@example.com"
    },
    "package_content": {
        "transformers": [
            {
                "name": "MyGreeter",
                "latest_version": 1,
                "versions": [
                    {
                        "name": "example.my-package-deprecated.MyGreeter",
                        "version": 1,
                        "categories": [
                            "Integrations"
                        ],
                        "aliases": [],
                        "visible": false
                    }
                ],
                "description": "# example.my-package.MyGreeter\n\n_This doc appears when the transformer is selected in the Workbench Quick Add pane._\n\nThe MyGreeter transformer takes a first name as input,\nand outputs a greeting for that person.\n\nThis transformer is part of the\n[example.my-package FME Package](https://hub.fme.co/publishers/example/packages/my-package).\n\n\n## Inputs:\n\n* **First Name**: The first name of who to greet. Default: \"World\".\n\n## Outputs attributes:\n\n* **greeting**: This attribute contains the greeting message.\n  It looks something like \"Hello, [first name]!\".\n",
                "description_format": "md"
            },
            {
                "name": "MyYeller",
                "latest_version": 2,
                "versions": [
                    {
                        "name": "example.my-package-deprecated.MyYeller",
                        "version": 2,
                        "categories": [
                            "Integrations"
                        ],
                        "aliases": [],
                        "visible": false
                    }
                ],
                "description": "# example.my-package.MyYeller\n\n_This doc appears when the transformer is selected in the Workbench Quick Add pane._\n\nThe MyYeller transformer takes a first name as input,\nand outputs a greeting for that person.\n\nThis transformer is part of the\n[example.my-package FME Package](https://hub.fme.co/publishers/example/packages/my-package).\n\n\n## Inputs:\n\n* **First Name**: The first name of who to greet. Default: \"World\".\n\n## Outputs attributes:\n\n* **greeting**: This attribute contains the greeting message.\n  It looks something like \"Hello, [first name]!\".\n",
                "description_format": "md"
            }
        ],
        "formats": [],
        "web_services": []
    },
    "categories": [
        "Integrations"
    ]
}
